<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Bootstrap theme</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Home</a></li>
                <?php if ($auth->isAuth()) : ?>
                    <li><a href="#">You are logged in as <?=$auth->getLogin()?></a></li>
                    <li><a href="/auth.php?log_out=1">(Logout)</a></li>
                <?php endif; ?>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>
<br><br><br><br><br>
<div class="container">
    <div class="row">
        <div class="col-lg-5">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Sign in</h3>
                    <?php if ($auth->error) : ?>
                        <h2> Login or password are wrong!</h2>
                    <?php endif; ?>
                </div>
                <div class="panel-body">
                    <form action="" method="post">
                        <div class="form-group input-group">
                            <span class="input-group-addon"><i class="fa fa-user fa-fw"></i></span>
                            <input type="text" name="login" class="form-control" value="" placeholder="login" maxlength="255" required />
                        </div>

                        <div class="form-group input-group">
                            <span class="input-group-addon"><i class="fa fa-lock fa-fw"></i></span>
                            <input type="password" name="pass" class="form-control" placeholder="password" required />
                        </div>

                        <div class="checkbox">
                            <label>
                                <input type="checkbox" name="rememberMe" value="1" checked /> Remember me
                            </label>
                        </div>

                        <input type="submit" value="Sign In" class="btn btn-primary"/>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>